server:
  port: 8080
security:
  basic:
    enabled: false
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/findandplay
    username: postgres
    password: postgres
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true
  #  boot:
  #    admin:
  #      url: http://localhost:8082