server:
  port: 8080
security:
#  basic:
#    enabled: false
  oauth2:
    client:
      client-id: clientapp
      client-secret: 123456
      authorized-grant-types: password, refresh_token
      authorities: USER
      scope: read,write
      resource-ids: restservice
      access-token-validity-seconds: 1800
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/findandplay
    username: postgres
    password: postgres
    platform: postgres
  jdbc_datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/findandplay
      username: postgres
      password: postgres
      platform: postgres
      hikari:
        idle-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true
      hibernate:
        format_sql: true
  #  boot:
  #    admin:
  #      url: http://localhost:8082