server:
  port: 8082
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/findapartner
        username: postgres
        password: postgres
        platform: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true